### ISSUE TITLE
aws_instance.bastion: Expected 1 AMI for ID: ami-1a6cc07a, got none

### ISSUE THREAD

**Issue by stabenfeldt** [ngerakines/terraform-docker-swarm-aws#1]
Hi,

Really good blog post you wrote. This is exactly what I'm looking for! :)

I cloned your repo and ran `terraform apply`.
But I get this error:
```bash
* aws_instance.bastion: Expected 1 AMI for ID: ami-1a6cc07a, got none
```

Any idea what might cause it?

**Comment by ngerakines** [comment]
That AMI is built and created via packer. You'll have to create the AMI and update your local configuration first.

**Comment by stabenfeldt** [comment]
Oh, yeah. I had overlooked that part from your article. Thanks! :)

I have a small suggestion that I think will make it easier for newbies like me to follow:
> When using this for your own images, be sure to change the subnet_id and security_group_ids attributes to the outputted vpc_subnet_a and sg_bastion values printed by `terraform output`

You mention terraform output on the very start, but when digesting a lot of new material one might not remember that detail. :)

**Comment by alienrobotarmy** [comment]
I ran into this as well, when trying to use an official amazon AMI. Looking closer it turns out I was trying to use an Instance Store AMI vs EBS backed.
Once I switched to an EBS backed terraform had no issues.
