### ISSUE TITLE
 aws_instance.bastion: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'terraform-key' does not exist

### ISSUE THREAD

**Issue by stabenfeldt** [ngerakines/terraform-docker-swarm-aws#2]
Hi,

Can you please help with some details on how to create the keypair?
I tried `ssh-keygen -b 2048 -t rsa -f ~/.ssh/terraform-key` and then refer to that key from *bastion.tf* and *swarm.tf*. 

But that does not work.
```
* aws_instance.bastion: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'terraform-key' does not exist
        status code: 400, request id: 1fff4eed-711a-48ea-9f4d-7d86934821b9
````

What should I do? This is how I have replaced foo in the settings:
```

$ grep -1 terraform-key *
bastion.tf-    associate_public_ip_address = "true"
bastion.tf:    key_name = "terraform-key"
bastion.tf-    subnet_id = "${aws_subnet.a.id}"
--
--
bastion.tf-      user = "ubuntu"
bastion.tf:      private_key = "${file("~/.ssh/terraform-key")}"
bastion.tf-      agent = false
--
--
swarm.tf-    associate_public_ip_address = "true"
swarm.tf:    key_name = "terraform-key"
swarm.tf-    subnet_id = "${aws_subnet.a.id}"
--
--
swarm.tf-      user = "ubuntu"
swarm.tf:      private_key = "${file("~/.ssh/terraform-key")}"
swarm.tf-      agent = false
--
--
swarm.tf-    associate_public_ip_address = "true"
swarm.tf:    key_name = "terraform-key"
swarm.tf-    subnet_id = "${aws_subnet.a.id}"
--
--
swarm.tf-      user = "ubuntu"
swarm.tf:      private_key = "${file("~/.ssh/terraform-key")}"
swarm.tf-      agent = false
--
--
swarm.tf-    user = "ubuntu"
swarm.tf:    private_key = "${file("~/.ssh/terraform-key")}"
swarm.tf-    agent = false
```

**Comment by ngerakines** [comment]
I think what needs to happen is that an SSH key needs to be created  as an AWS resource and then it referenced throughout the sources. In the two places (sawm.tf and bastion.tf) where the key is referenced, it expects that key to exist within AWS already.

**Comment by stabenfeldt** [comment]
You were right. I wrote 1 line on how to do that in the README: https://github.com/stabenfeldt/terraform-docker-swarm-aws/commit/f328906ba39180463c85f2561d780f8b75673528

I'll create a PR when I'm able to get everything up and running. Adding small notes of documentation where needed.
